### ISSUE TITLE
4 numeric pin too weak

### ISSUE THREAD

**Issue by goerick** [EPICMC/BridgeAuth#4]
The pin is too weak and that means there is concurrent pins and as well as only 8999 possibilities to brute force (takes less than a second).

Pins should have *atleast* 10 alphanumeric characters

**Comment by DALTONTASTIC** [comment]
Enable IP Security

**Comment by DALTONTASTIC** [comment]
It doesn't matter if there is concurrent pins lmao..... It's a password it doesn't have to be unique.

**Comment by legoboy0215** [comment]
But I generate my token from my pc!

**Comment by DALTONTASTIC** [comment]
so?

**Comment by DALTONTASTIC** [comment]
Bridge tokens are now 10 characters long and alphanumeric.

These letters and numbers aren't used due to confusion: O, 0, l, 1

**Comment by goerick** [comment]
Sorry the wording of that sucks because I was busy at that time. Thanks for the fix <3
